// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-NPdREejg2wgFogsy5Zq7wiRGrVQX6ic',
    appId: '1:1042563582649:web:8635d64766ef63a5ee6968',
    messagingSenderId: '1042563582649',
    projectId: 'cotizador-supermercado',
    authDomain: 'cotizador-supermercado.firebaseapp.com',
    storageBucket: 'cotizador-supermercado.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoE85xAJS6HYEJEx-tnh0WZNU8AofKrQc',
    appId: '1:1042563582649:android:7a4e49c451f4e22aee6968',
    messagingSenderId: '1042563582649',
    projectId: 'cotizador-supermercado',
    storageBucket: 'cotizador-supermercado.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWUatsJ1gOamKHYLD2bTtZI75u0VNqefQ',
    appId: '1:1042563582649:ios:cf47dd897f2719a6ee6968',
    messagingSenderId: '1042563582649',
    projectId: 'cotizador-supermercado',
    storageBucket: 'cotizador-supermercado.firebasestorage.app',
    iosBundleId: 'com.example.cotizadorSupermercado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWUatsJ1gOamKHYLD2bTtZI75u0VNqefQ',
    appId: '1:1042563582649:ios:cf47dd897f2719a6ee6968',
    messagingSenderId: '1042563582649',
    projectId: 'cotizador-supermercado',
    storageBucket: 'cotizador-supermercado.firebasestorage.app',
    iosBundleId: 'com.example.cotizadorSupermercado',
  );
}
